### ISSUE TITLE
Layer for Python 3.9

### ISSUE THREAD

**Issue by nayaverdier** [alexanderluiscampino/lambda-layers#3]
I have been using your layer for python 3.7, and it's been a massive lifesaver. I'm having difficulty building a similar layer for python 3.9. Do you have one already built somewhere, or instructions that might help to build it?

**Comment by alexanderluiscampino** [comment]
I dont right now, last time I tried I failing creating the binding. But I can put sometime on that soon to be honest.

**Comment by nayaverdier** [comment]
@alexanderluiscampino I just got a 3.9 layer working by taking your 3.7 layer, and replacing the `python` directory with output of running `pip install pyodbc==4.0.26 -t python` on the docker image `public.ecr.aws/sam/build-python3.9:latest`.

For some reason using the latest pyodbc version did not work properly, it just wasn't picking up the driver at runtime.

Let me know if you'd like me to make a PR to add `pyodbc39.zip`

**Comment by alexanderluiscampino** [comment]
Thats awesome, sorry have been on vacation haven't had the time to try it. 

Would you mind opening a PR?  I'd also like to ask to add whatever script you used, so I can replicate on my end. I intend to have a recipe to create these layers. 

You didn't have to modify the ini files at all for it to work?

**Comment by nayaverdier** [comment]
Nope, I didn't have to modify the ini files at all! I just opened the PR and included the steps to build there.

**Comment by alexanderluiscampino** [comment]
Ah, I see why. You're reusing the 3.7 files and just overwriting for 3.9
using your script. Smart.
